[package]
name = "snake"
version = "0.1.0"
authors = ["Sugi <sugidaffection@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.43.0"
piston2d-graphics = "0.32.0"
piston2d-opengl_graphics = "0.62.0"
pistoncore-glutin_window = "0.55.0"